/*
Author: KMC20
Date: 2024/7/4
Function: Generate the square root results offline for DRIM-ANN.
Usage:
 > g++ genSquareRoots.cpp -std=c++11 -I ../DRIM-ANN/common/inc -o genSquareRoots
 > ./genSquareRoots -M 8 -s ../DRIM-ANN/offlineFiles/squareRootsUint16
 > rm genSquareRoots
*/

#include <fstream>
#include <iostream>
#include <vector>
#include <string>
#include "request.h"
#include <getopt.h>

#define NR_JOB_PARALLEL 64

__attribute__((noreturn)) static void usage(FILE *f, int exit_code, const char *exec_name) {
    /* clang-format off */
    fprintf(f,
            "\nusage: %s [-s <square_result_path>] [-M <number_of_subvectors>]\n"
            "\n"
            "\t-s \tthe path to the file to save the square result (default: squareRootsUint16)\n"
            "\t-M \tthe number of subvectors generated by each point (default: 8)\n"
            "\t-h \tshow the usage message\n",
            exec_name);
    /* clang-format on */
    exit(exit_code);
}

static void parse_args(int argc, char **argv, int *sliceAmt, std::string &squareRootsFileName) {
    int opt;
    extern char *optarg;
    while ((opt = getopt(argc, argv, "hs:M:")) != -1) {
        switch (opt) {
            case 'M':
                *sliceAmt = (int)atoi(optarg);
                break;
            case 's':
                squareRootsFileName = optarg;
                break;
            case 'h':
                usage(stdout, EXIT_SUCCESS, argv[0]);
            default:
                usage(stderr, EXIT_FAILURE, argv[0]);
        }
    }
}


int main(int argc, char **argv)
{
    int sliceAmt = 8;
    std::string squareRootsFileName = "squareRootsUint16";
    parse_args(argc, argv, &sliceAmt, squareRootsFileName);
    std::vector<VECSUMTYPE> res(LARGE_SQUARE_RES_SIZE);
    #pragma omp parallel for num_threads(NR_JOB_PARALLEL)
    for (VECSUMTYPE elem = 0; elem < LARGE_SQUARE_RES_SIZE; ++elem)
        res[elem] = elem * elem;
    std::fstream file;
    file.open(squareRootsFileName, std::ios::out | std::ios::binary);
    if (!file.is_open()) {
        std::cerr << "Failed to open the output square root result file: " << squareRootsFileName << "! Exit now!" << std::endl;
        file.close();
        return -1;
    }
    file.write(reinterpret_cast<char *>(res.data()), LARGE_SQUARE_RES_SIZE * sizeof(VECSUMTYPE));
    file.close();
    return 0;
}